# Uncomment the next line to define a global platform for your project
platform :ios, '9.3'

target 'GitHubKMP' do
  # Uncomment the next line if you're not using Swift and don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for GitHubKMP
  pod 'SDWebImage', '~> 5.0', :modular_headers => true

end
